name: plataformav1
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-261.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0

  geolocator: ^9.0.2
  flutter_osm_plugin: ^0.53.4+1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

assets:
  - assets/images/
